### ISSUE TITLE
Testing for Search

### ISSUE THREAD

**Issue by Pma913** [streeteatz/streateatz-fe#37]
test functionality of search component

As user I should be able to:
- [x] locate a search bar
  - [x] fill in the search bar
  - [x] hit search icon
  - [x] see display of cards
- [x] favorite a card (or two)
  - [x] find the favorites button
  - [x] click the button
  - [x] see only favorited card(s)
- [ ] hit clear and see the original array of cards

**Comment by JacobMacFarlane** [comment]
I will get on this asap no rocky
